[package]
name = "rustyapa"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "parser",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.58", features = ["derive"] }

[dependencies]
clap = { workspace = true }
parser = { path = "parser" }